import{i as u,S as d}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const l=document.querySelector("#form"),s=document.querySelector(".loader"),a=document.querySelector(".gallery"),m={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};s.style.display="none";document.addEventListener("DOMContentLoaded",()=>{l.addEventListener("submit",r=>{r.preventDefault();const i=document.getElementById("search").value.trim();i&&(s.style.display="inline-block",a.innerHTML="",fetch(`https://pixabay.com/api/?key=42390254-a1d01e86edd47d7ed3c2f6c78&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>o.json()).then(o=>c(o)).catch(o=>{console.error("Error fetching data:",o)}).finally(()=>{s.style.display="none"}))});function c(r){if(r.hits.length===0)u.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const i=r.hits.map(e=>`<li class="gallery-item"><a href="${e.webformatURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <div class='comments'>
          <p><b>Likes: </b>${e.likes}</p>
          <p><b>Views: </b>${e.views}</p>
          <p><b>Comments: </b>${e.comments}</p>
          <p><b>Downloads: </b>${e.downloads}</p>
          </div>
          </li>`).join("");a.insertAdjacentHTML("afterbegin",i),new d(".gallery a",m).refresh(),l.reset()}}});
//# sourceMappingURL=commonHelpers.js.map
