import{S as u}from"./assets/vendor-874053e3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();function m(n){return fetch(`https://pixabay.com/api/?key=42390254-a1d01e86edd47d7ed3c2f6c78&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`).then(r=>r.json())}function d(n,r,i,s){if(n.hits.length===0)iziToast.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const e=n.hits.map(o=>`<li class="gallery-item"><a href="${o.webformatURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
          <div class='comments'>
          <p><b>Likes: </b>${o.likes}</p>
          <p><b>Views: </b>${o.views}</p>
          <p><b>Comments: </b>${o.comments}</p>
          <p><b>Downloads: </b>${o.downloads}</p>
          </div>
          </li>`).join("");r.insertAdjacentHTML("afterbegin",e),new u(".gallery a",i).refresh(),s.reset()}}const l=document.querySelector("#form"),c=document.querySelector(".loader"),a=document.querySelector(".gallery"),p={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};c.style.display="none";document.addEventListener("DOMContentLoaded",()=>{l.addEventListener("submit",n=>{n.preventDefault();const r=document.getElementById("search").value.trim();r&&(c.style.display="inline-block",a.innerHTML="",m(r).then(i=>d(i,a,p,l)).catch(i=>{console.error("Error fetching data:",i)}).finally(()=>{c.style.display="none"}))})});
//# sourceMappingURL=commonHelpers.js.map
